### ISSUE TITLE
Add support for multiple CRD  versions

### ISSUE THREAD

**Issue by lepiolet** [appgate/sdp-operator#140]
We should support different CRD versions for different appgate versions simultaneously in the same cluster

**Comment by mandopaloooza** [comment]
We added version suffixes to our CRDs. All CRDs are now installed as part of a [CRD helm chart](https://github.com/appgate/sdp-operator/pkgs/container/charts%2Fsdp-operator-crd). Users can deploy multiple instances of the SDP Operator on the cluster with different API version values.
