### ISSUE TITLE
Support k8s > 1.16

### ISSUE THREAD

**Issue by lepiolet** [appgate/sdp-operator#141]
There are some changes when creating CRD:
  1. API version `v1beta1` has been deprecated
  2. a json schema is required now for each CRD (we should be able to derive this automatically from the open spec API)

**Comment by israel-morales** [comment]
any updates to this issue?  We are running 1.22.4 and cannot deploy the CRDs.  Thank you!

**Comment by defcy35** [comment]
Much appreciate the update! Is there an ETA on when this might get updated? Thanks!
