### ISSUE TITLE
Add support for controller certificate in appgate-operator-conf configmap

### ISSUE THREAD

**Issue by thomascellerier** [appgate/sdp-operator#64]
Right now we don't verify the server certificate which is obviously not OK for v1.

**Comment by lepiolet** [comment]
I will add a flag to enable/disable this feature.

**Comment by lepiolet** [comment]
https://github.com/appgate/sdp-operator/pull/75 This allows to ignore SSL verification when using self signed certificates

**Comment by lepiolet** [comment]
https://github.com/appgate/sdp-operator/pull/77 This issue is fixed here. Only used for the connections to the appgate collective.
