### ISSUE TITLE
The latest version of the base image we use for running the linter and the tests does no work anymore

### ISSUE THREAD

**Issue by lepiolet** [appgate/sdp-operator#73]
`python:rc-slim` has been updated and now the build seems to be broken.

**Comment by thomascellerier** [comment]
Yes I think we should move to `python:3.9-slim` and fix eventual issues.

**Comment by lepiolet** [comment]
yeah, this is what that image contains now
```
root@de65358585c7:~# python3 --version
Python 3.10.0a1
```
